module.exports = {
  'no-var': 2,
  'no-console': 2,
  'no-debugger': 2,
  'no-alert': 2,
  'no-caller': 2,
  'no-eval': 2,
  'no-extra-bind': 2,
  'no-extra-label': 2,
  'no-implicit-globals': 2,
  'no-implied-eval': 2,
  'no-labels': 2,
  'no-unused-expressions': 2,
  'no-void': 2,
  'no-with': 2,
  'no-delete-var': 2,
  'no-process-env': 2,
  'key-word-spacing': 2,
  'no-continue': 2,
  'no-new-func': 2,
};
