module.exports = {
  // .
  'dot-location': 2,
  'dot-notation': 2,
  // ===
  'eqeqeq': 2,
  // ,
  'no-sequences': 2,
  'comma-dangle': 2,
  'comma-spacing': 2,
  'comma-style': 2,
  'multiline-ternary': 2,
  'no-nested-ternary': 2,
  'no-ternary': 2,
  'no-unneeded-ternary': 2,
  'no-bitwise': 2,
  'no-mixed-operators': 2,
  'no-plusplus': 2,
  'operator-assignment': 2,
  'operater-linebreak': 2,
  'quotes': 2,
  'semi': 2,
  'semi-spacing': 2,
  'semi-style': 2,
  'space-infix-ops': 2,
  'space-unary-ops': 2,
};
