module.exports = {
  'use-isnan': 2,
  'no-extend-native': 2,
  'no-global-assign': 2,
  'no-iterator': 2,
  'no-new': 2,
  'no-new-wrappers': 2,
  'no-octal': 2,
  'no-redeclare': 2,
  'no-restricted-properties': 2,
  'no-return-assign': 2,
  'no-return-await': 2,
  'no-self-assign': 2,
  'no-restricted-globals': 2,
  'no-undef': 2,
  'no-undefined': 2,
  'no-unused-vars': 2,
  'no-use-before-define': 2,
  'camelcase': 2,
  'id-blacklist': 2,
  'id-length': 2,
  'id-match': 2,
  'no-duplicate-imports': 2,
  'no-restricted-imports': 2,
  'no-useless-rename': 2,
  'prefer-const': 2,
};